----------------------------------------------------------------------------------------------------------
--
--  File Name:              cor_filterbanks_filterbanks_reg.vhd
--  Type:                   RTL
--  Template Rev:           1.0
--
--  Title:
--  Description:
--
--          Generated by Automatic Register Generation System (ARGS) from cor_filterbanks.peripheral.yaml
--
----------------------------------------------------------------------------------------------------------

LIBRARY IEEE, axi4_lib, common_lib, technology_lib;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE axi4_lib.axi4_lite_pkg.ALL;
USE common_lib.common_mem_pkg.ALL;
USE common_lib.common_pkg.ALL;
USE technology_lib.technology_pkg.ALL;
USE technology_lib.technology_select_pkg.ALL;
USE work.cor_filterbanks_filterbanks_reg_pkg.ALL;

-------------------------------------------------------------------------------
--                              ENTITY STATEMENT                             --
-------------------------------------------------------------------------------

entity cor_filterbanks_filterbanks_versal is
    GENERIC (g_technology : t_technology := c_tech_select_default);
    PORT (
        MM_CLK              : IN    STD_LOGIC;
        MM_RST              : IN    STD_LOGIC;
        noc_wren            : IN STD_LOGIC;
        noc_rden            : IN STD_LOGIC;
        noc_wr_adr          : IN STD_LOGIC_VECTOR(17 DOWNTO 0);
        noc_wr_dat          : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
        noc_rd_adr          : IN STD_LOGIC_VECTOR(17 DOWNTO 0);
        noc_rd_dat          : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
        CONFIG_FIELDS_RW			: OUT t_config_rw;
        CONFIG_FIELDS_RO			: IN  t_config_ro;
		CONFIG_OUTPUT_DISABLE_IN	: IN  t_config_output_disable_ram_in;
		CONFIG_OUTPUT_DISABLE_OUT	: OUT t_config_output_disable_ram_out
        );
end cor_filterbanks_filterbanks_versal;

-------------------------------------------------------------------------------
--                           ARCHITECTURE STATEMENT                          --
-------------------------------------------------------------------------------

architecture rtl of cor_filterbanks_filterbanks_versal is

begin

    noc_rd_dat <= (others => '0');
    CONFIG_FIELDS_RW <= (others => (others => '0'));
    CONFIG_OUTPUT_DISABLE_OUT.rd_dat <= (others => '0');
    CONFIG_OUTPUT_DISABLE_OUT.rd_val <= '0';
    
end rtl;
