--
-- FB_top.vhd
-- Author : David Humphrey (dave.humphrey@csiro.au)
-- Description
--  Top level for the correlator filterbanks. Includes :
--   - Correlator filterbank - 4096 point FFT, 12 tap FIR filter, 4 streams simultaneously.
--   - Fine delay
--   - MACE interface, which is just to allow reading/writing of the filter taps in the filterbanks.
--     *** WARNING *** MACE slave is manually written. MACE slave module is NOT auto-generated by ARGS. 
--     Changing the yaml file will not change the actual registers.
--     This is to allow the memories to reside in the filters, rather than being pulled out and put into 
--     ARGs. 
--
----------------------------------------------------------------------------------------------------------
library IEEE, axi4_lib, common_lib, filterbanks_lib, dsp_top_lib;
library xpm, correlator_lib, noc_lib, signal_processing_common;

use dsp_top_lib.dsp_top_pkg.all;
use common_lib.common_pkg.all;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;
use axi4_lib.axi4_lite_pkg.ALL;
use axi4_lib.axi4_full_pkg.ALL;
use xpm.vcomponents.all;
use filterbanks_lib.cor_filterbanks_filterbanks_reg_pkg.ALL;
use signal_processing_common.target_fpga_pkg.ALL;

entity FB_Top_correlator is
    generic(
        -- For the U55, 4 parallel filterbanks, so filterbanks/2 = 2
        -- For the V80, 12 parallel filterbanks, so filterbanks/2 = 6
        g_FILTERBANKS_div2 : integer := 2
    );
    port(
        i_data_rst  : in std_logic;
        -- AXI slave interface, 64k word block of space with the fir filter coefficients.
        i_axi_clk  : in std_logic;
        i_axi_clk_2x : in std_logic;
        i_axi_rst  : in std_logic;
        i_axi_mosi  : in  t_axi4_lite_mosi;
        o_axi_miso  : out t_axi4_lite_miso;
        -- Configuration (on i_data_clk)
        i_fineDelayDisable : in std_logic;
        -----------------------------------------
        -- data input, common valid signal, expects packets of 4096 samples. 
        -- Requires at least 2 clocks idle time between packets
        i_sof     : in std_logic;   -- Start of frame, occurs for every new set of channels.
        i_data    : in t_slv_32_arr(23 downto 0);  -- each 32-bit value has real in bits 15:0, imaginary in bits 31:16 
        i_meta_delays         : in t_CT1_META_delays_arr(11 downto 0); -- defined in DSP_top_pkg.vhd; fields are : HDeltaP(31:0), VDeltaP(31:0), HOffsetP(31:0), VOffsetP(31:0), bad_poly (std_logic)
        i_meta_RFIThresholds  : in t_slv_32_arr(11 downto 0);
        i_meta_integration    : in std_logic_vector(31 downto 0);
        i_meta_ctFrame        : in std_logic_vector(1 downto 0);
        i_meta_virtualChannel : in std_logic_vector(11 downto 0); -- first virtual channel output, remaining 3 (U55c) or 11 (V80) are o_meta_VC+1, +2, etc.
        i_meta_valid          : in std_logic_vector(11 downto 0); -- Total number of virtual channels need not be a multiple of 12, so individual valid signals here.
        i_lastChannel         : in std_logic; -- aligns with meta data, indicates this is the last group of channels to be processed in this frame.
        -- o_demap_table_select will change just prior to the start of reading out of a new integration frame.
        -- So it should be registered on the first output of a new integration frame in corner turn 2.
        i_demap_table_select  : in std_logic;
        i_dataValid : in std_logic;
        
        -- Correlator filterbank data output
        o_integration    : out std_logic_vector(31 downto 0); -- Which integration frame is this ? Units of 0.849 seconds since epoch.
        o_ctFrame        : out std_logic_vector(1 downto 0);  -- Which 283ms corner turn frame is this ? 
        o_virtualChannel : out t_slv_16_arr(11 downto 0); -- up to 12 virtual channels in parallel
        o_bad_poly       : out std_logic_vector(2 downto 0);
        o_lastChannel    : out std_logic;  -- Last of the group of 4 channels
        o_demap_table_select : out std_logic;
        o_HeaderValid : out std_logic_vector(11 downto 0);
        o_Data        : out t_ctc_output_payload_arr(11 downto 0);
        o_DataValid   : out std_logic;
        -- i_SOF delayed by 16384 clocks;
        -- i_sof occurs at the start of each new block of 4 virtual channels.
        -- Delay of 16384 is enough to ensure that o_sof falls in the gap
        -- between data packets at the filterbank output that occurs due to the filterbank preload.
        o_sof : out std_logic
    );

    -- prevent optimisation across module boundaries.
    attribute keep_hierarchy : string;
    attribute keep_hierarchy of FB_Top_correlator : entity is "yes";
    
end FB_Top_correlator;

architecture Behavioral of FB_Top_correlator is
    
    signal FDdata  : t_ctc_output_payload_arr(11 downto 0);
    
    signal firtap_addr : std_logic_vector(15 downto 0);
    --signal firtap_clk : std_logic;
    signal cor_we : std_logic;
    signal corFirRd_data : std_logic_vector(17 downto 0);
    signal firtap_wr_data : std_logic_vector(17 downto 0);
    
    signal CorDin0, CorDin1, CorDin2, CorDin3 : t_slv_8_arr(1 downto 0);
    type t_slv_308_arr is array(5 downto 0) of std_logic_vector(307 downto 0);
    signal CorrelatorMetaIn, corMetaOut : t_slv_308_arr;
    signal CorDout0, CorDout1, CorDout2, CorDout3 : t_slv_16_arr(1 downto 0);
    signal CorValidOut, CorValidOutDel : std_logic_vector(11 downto 0);
    
    signal FDcorDataValid : std_logic_vector(3 downto 0);
    
    signal corFBHeader : t_CT1_META_out_arr(3 downto 0);
    signal corDout_arr : t_FB_output_payload_a(3 downto 0);
    
    signal FDHeader : t_CT1_META_out_arr(3 downto 0);
    signal DataValid : std_logic;
    
    signal corFBDout : t_slv_32_arr(23 downto 0);
    signal corFBHeaderValid : std_logic_vector(5 downto 0);
    
    signal captureCount : std_logic_vector(3 downto 0);
    signal FDcorDataValidDel1 : std_logic;
    signal captureData : t_slv_256_arr(7 downto 0);
    
    signal triggerRdLow128bits : std_logic_vector(6 downto 0) := "0000000";
    signal triggerRdHigh128bits : std_logic_vector(6 downto 0) := "0000000";
    signal copyToUramCount : std_logic_Vector(2 downto 0);
    signal copyToUramValidLow, copyToUramValidHigh, copyToUramValidLowDel1, copyToUramValidHighDel1 : std_logic := '0';
    signal bufWrAddrDoubleBufferSelect : std_logic := '0';
    signal bufWrAddrBuffer, bufWrAddrBufferAdv : std_logic_vector(2 downto 0);
    signal bufWrAddrWord : std_logic_vector(8 downto 0);
    signal bufRdAddrDoubleBufferSelect : std_logic := '0';
    signal bufRdAddrBuffer, bufRdAddrBufferDel1, bufRdAddrBufferDel2, bufRdAddrBufferDel3 : std_logic_vector(2 downto 0);
    signal bufRdAddrWord : std_logic_vector(8 downto 0);
    signal bufWE : std_logic_vector(0 downto 0);
    type sendTo100GE_fsm_t is (start, checkEnable, checkEnableWait0, checkEnableWait1, checkEnableWait2, checkEnableWait3, waitReady, sendHeader, sendData, nextBuffer, done);
    signal sendTo100GE_fsm : sendTo100GE_fsm_t := done;
    signal sendTo100GE_fsm_del1, sendTo100GE_fsm_del2, sendTo100GE_fsm_del3 : sendTo100GE_fsm_t := done;

    signal bufWrData, bufDout : std_logic_vector(127 downto 0);
    signal triggerSendTo100GE : std_logic;
    signal vc_hold, vc_out : t_slv_16_arr(3 downto 0);
    signal integration_hold, integration_out : std_logic_vector(31 downto 0);
    signal bufWrAddr, bufRdAddr : std_logic_vector(12 downto 0);
    signal config_ro : t_config_ro;
    signal output_disable_i : t_config_output_disable_ram_in;
    signal output_disable_o : t_config_output_disable_ram_out;
    signal tx_packet_count_ct : std_logic_vector(31 downto 0) := x"00000000";
    signal FDcorDataValidDel : std_logic;
    signal output_disabled : std_logic;
    signal output_disable_addr : std_logic_vector(9 downto 0);
    signal reg_reset_del1, reg_reset : std_logic;
    signal config_rw : t_config_rw;
    signal HeaderValid : std_logic_vector(3 downto 0);
    signal sof_out, sof_del1 : std_logic := '0';
    signal sof_out_count : std_logic_vector(13 downto 0) := (others => '0');
    signal RFIScale : std_logic_vector(4 downto 0);
    signal RFI_threshold : t_slv_32_arr(3 downto 0);
    
    signal noc_wren         : STD_LOGIC;
    signal noc_rden         : STD_LOGIC;
    signal noc_wr_adr       : STD_LOGIC_VECTOR(17 DOWNTO 0);
    signal noc_wr_dat       : STD_LOGIC_VECTOR(31 DOWNTO 0);
    signal noc_rd_adr       : STD_LOGIC_VECTOR(17 DOWNTO 0);
    signal noc_rd_dat       : STD_LOGIC_VECTOR(31 DOWNTO 0);
    signal noc_rd_dat_mux   : STD_LOGIC_VECTOR(31 DOWNTO 0);
    signal markRFI : std_logic_vector(3 downto 0);
    signal mark_RFI : std_logic_vector(11 downto 0);
    
    signal dataIn :  t_slv_32_arr(23 downto 0);
    signal RFIThresholds  : t_slv_32_arr(11 downto 0);
    
begin
    
    -----------------------------------------------------------------------------------
    -- correlator Filterbank
    process(i_axi_clk)
    begin
        if rising_edge(i_axi_clk) then

            for i in 0 to 5 loop
                CorrelatorMetaIn(i)(31 downto 0) <= i_meta_delays(2*i+0).HDeltaP;
                CorrelatorMetaIn(i)(63 downto 32) <= i_meta_delays(2*i+0).VDeltaP;
                CorrelatorMetaIn(i)(95 downto 64) <= i_meta_delays(2*i+0).HOffsetP;
                CorrelatorMetaIn(i)(127 downto 96) <= i_meta_delays(2*i+0).VOffsetP;
                
                CorrelatorMetaIn(i)(128+31 downto 128+0) <= i_meta_delays(2*i+1).HDeltaP;
                CorrelatorMetaIn(i)(128+63 downto 128+32) <= i_meta_delays(2*i+1).VDeltaP;
                CorrelatorMetaIn(i)(128+95 downto 128+64) <= i_meta_delays(2*i+1).HOffsetP;
                CorrelatorMetaIn(i)(128+127 downto 128+96) <= i_meta_delays(2*i+1).VOffsetP;
                
                CorrelatorMetaIn(i)(267 downto 256) <= std_logic_vector(unsigned(i_meta_virtualChannel) + 2*i);
                CorrelatorMetaIn(i)(268) <= i_meta_delays(2*i+0).bad_poly;
                CorrelatorMetaIn(i)(269) <= i_meta_delays(2*i+1).bad_poly;
                CorrelatorMetaIn(i)(271 downto 270) <= i_meta_ctFrame;
                CorrelatorMetaIn(i)(303 downto 272) <= i_meta_integration;
                CorrelatorMetaIn(i)(304) <= i_meta_valid(2*i+0); -- note that .valid is just a qualifier for the meta data. The meta data is only valid if both this and i_datavalid are high.
                CorrelatorMetaIn(i)(305) <= i_meta_valid(2*i+1);
                CorrelatorMetaIn(i)(306) <= i_lastChannel;
                CorrelatorMetaIn(i)(307) <= i_demap_table_select;
            end loop;
            
            dataIn <= i_data;
            RFIThresholds <= i_meta_RFIThresholds;
            DataValid <= i_DataValid;
            
            -- Generate o_sof from i_sof, taking into account the latency of the filterbank processing.
            sof_del1 <= i_sof;
            if i_sof = '1' and sof_del1 = '0' then
                sof_out_count <= (others => '1'); -- 16383
            elsif (unsigned(sof_out_count) /= 0) then
                sof_out_count <= std_logic_vector(unsigned(sof_out_count) - 1);
            end if;
            if (unsigned(sof_out_count) = 1) then
                sof_out <= '1';
            else
                sof_out <= '0';
            end if;
            o_sof <= sof_out;
        end if;
    end process;
    
    
    FBgen : for i in 0 to (g_FILTERBANKS_div2-1) generate
    
        -- Each instance of correlatorFBTop25 processes data for 2 virtual channels.
        -- (2 Virtual channels) * (2 pol per channel) = 4 data inputs
        corfbi : entity filterbanks_lib.correlatorFBTop25
        generic map(
            METABITS => 308,    -- Width in bits of the meta_i and meta_o ports.
            FRAMESTODROP => 11  -- Number of output frames to drop after a reset (to account for initialisation of the filterbank)
        ) port map (
            -- processing clock
            clk     => i_axi_clk,
            clk_2x  => i_axi_clk_2x,
            rst     => i_SOF,
            -- Data input, common valid signal, expects packets of 4096 samples. 
            -- Requires at least 2 clocks idle time between packets.
            i_data0 => dataIn(i*4+0), -- in (31:0);  4 Inputs, each complex data, 8 bit real, 8 bit imaginary.
            i_data1 => dataIn(i*4+1), -- in (31:0);
            i_data2 => dataIn(i*4+2), -- in (31:0);
            i_data3 => dataIn(i*4+3), -- in (31:0);
            i_RFI_threshold01 => RFIThresholds(i*2 + 0),
            i_RFI_threshold23 => RFIThresholds(i*2 + 1),
            meta_i  => correlatorMetaIn(i), -- in std_logic_vector((METABITS-1) downto 0);  -- Sampled on the first cycle of every third packet of valid_i. 
            valid_i => DataValid,    -- in std_logic;
            -- Data out; bursts of 216 clocks for each channel.
            o_data0 => corFBDout(i*4+0), -- out (31:0);   -- 4 outputs, real and imaginary parts in bits 15:0 and 31:16 respectively;
            o_data1 => corFBDout(i*4+1), -- out (31:0);
            o_data2 => corFBDout(i*4+2), -- out (31:0);
            o_data3 => corFBDout(i*4+3), -- out (31:0);
            mark_RFI01_o => mark_RFI(i*2 + 0), -- out std_logic;
            mark_RFI23_o => mark_RFI(i*2 + 1), -- out std_logic;
            meta_o  => corMetaOut(i),  -- out std_logic_vector((METABITS-1) downto 0);
            valid_o => corValidOut(i*2+0), -- out std_logic;
            -- Writing FIR Taps
            FIRTapData_i   => (others => '0'),  -- in (17:0);  For register writes of the filtertaps.
            FIRTapData_o   => open,             -- out (17:0); For register reads of the filtertaps. 3 cycle latency from FIRTapAddr_i
            FIRTapAddr_i   => (others => '0'),  -- in (15:0);  4096 * 12 filter taps = 49152 total.
            FIRTapWE_i     => '0',              -- in std_logic;
            FIRTapClk      => i_axi_clk         -- in std_logic;
        );
        corValidOut(i*2+1) <= corValidOut(i*2);
        -- Pack 16 bit data into the structure that goes into the fine delay module.
        corDout_arr(i*2+0).hpol.re <= corFBDout(i*4+0)(15 downto 0);
        corDout_arr(i*2+0).hpol.im <= corFBDout(i*4+0)(31 downto 16);
        corDout_arr(i*2+0).vpol.re <= corFBDout(i*4+1)(15 downto 0);
        corDout_arr(i*2+0).vpol.im <= corFBDout(i*4+1)(31 downto 16);
        corDout_arr(i*2+1).hpol.re <= corFBDout(i*4+2)(15 downto 0);
        corDout_arr(i*2+1).hpol.im <= corFBDout(i*4+2)(31 downto 16);
        corDout_arr(i*2+1).vpol.re <= corFBDout(i*4+3)(15 downto 0);
        corDout_arr(i*2+1).vpol.im <= corFBDout(i*4+3)(31 downto 16);
        
        corFBHeader(i*2+0).HDeltaP <= corMetaOut(i)(31 downto 0);
        corFBHeader(i*2+0).VDeltaP <= corMetaOut(i)(63 downto 32);
        corFBHeader(i*2+0).HOffsetP <= corMetaOut(i)(95 downto 64);
        corFBHeader(i*2+0).VOffsetP <= corMetaOut(i)(127 downto 96);
        corFBHeader(i*2+0).virtualChannel <= "0000" & corMetaOut(i)(267 downto 256);
        corFBHeader(i*2+0).valid <= corMetaOut(i)(304);
        corFBHeader(i*2+0).integration <= corMetaOut(i)(303 downto 272);
        corFBHeader(i*2+0).ctFrame <= corMetaOut(i)(271 downto 270);
        corFBHeader(i*2+0).bad_poly <= corMetaOut(i)(268);
        corFBHeader(i*2+0).lastChannel <= corMetaOut(i)(306);
        corFBHeader(i*2+0).demap_table_select <= corMetaOut(i)(307);
        
        corFBHeader(i*2+1).HDeltaP <= corMetaOut(i)(31+128 downto 128);
        corFBHeader(i*2+1).VDeltaP <= corMetaOut(i)(63+128 downto 32+128);
        corFBHeader(i*2+1).HOffsetP <= corMetaOut(i)(95+128 downto 64+128);
        corFBHeader(i*2+1).VOffsetP <= corMetaOut(i)(127+128 downto 96+128);
        corFBHeader(i*2+1).virtualChannel <= "0000" & std_logic_vector(unsigned(corMetaOut(i)(267 downto 256)) + 1);
        corFBHeader(i*2+1).valid <= corMetaOut(i)(305);
        corFBHeader(i*2+1).integration <= corMetaOut(i)(303 downto 272);
        corFBHeader(i*2+1).ctFrame <= corMetaOut(i)(271 downto 270);
        corFBHeader(i*2+1).bad_poly <= corMetaOut(i)(269);
        corFBHeader(i*2+1).lastChannel <= corMetaOut(i)(306);
        corFBHeader(i*2+1).demap_table_select <= corMetaOut(i)(307);
    
    end generate;
    
    corFBHeaderValid <= corValidOut and (not corValidOutDel);
    
    process(i_axi_clk)
    begin
        if rising_edge(i_axi_clk) then
            corValidOutDel <= corValidOut;
        end if;
    end process;
    
    FDGen : for i in 0 to (2*g_FILTERBANKS_DIV2 - 1) generate
        -- one fineDelay module per virtual channel
        FineDelay : entity filterbanks_lib.fineDelay
        generic map (
            FBSELECTION => 2  -- 2 = Correlator
        ) port map (
            i_clk  => i_axi_clk,
            -- data and header in
            i_data        => corDout_arr(i),    -- in t_FB_output_payload;  -- 16 bit data : .Hpol.re, Hpol.im, .Vpol.re, .Vpol.im 
            i_markRFI     => markRFI(i),        -- in std_logic;
            i_dataValid   => corValidOut(i),    -- in std_logic;
            i_header      => corFBHeader(i),    -- .HDeltaP(31:0), .VDeltaP(31:0), .HOffsetP(31:0), .VOffsetP(31:0), integration(31:0), ctFrame(1:0), virtualChannel(15:0);
            i_headerValid => corFBHeaderValid(0),  -- in std_logic;
            -- Data and Header out
            o_data        => FDdata(i),         -- out t_ctc_output_payload;   -- 8 bit data : .Hpol.re, Hpol.im, .Vpol.re, .Vpol.im 
            o_dataValid   => FDcorDataValid(i), -- out std_logic;
            o_header      => FDHeader(i),       -- .HDeltaP(31:0), .VDeltaP(31:0), .HOffsetP(31:0), .VOffsetP(31:0), integration(31:0), ctFrame(1:0), virtualChannel(15:0);
            o_headerValid => headerValid(i),    -- out std_logic;
            -------------------------------------------
            -- control and monitoring
            -- Disable the fine delay. Instead of multiplying by the output of the sin/cos lookup, just scale by unity.
            i_disable     => i_fineDelayDisable, -- in std_logic;
            -- Scale down by 2^(i_RFIScale) before clipping for RFI.
            -- Unity for the sin/cos lookup is 0x10000, so :
            --   i_RFIScale < 16  ==> Amplify the output of the filterbanks.
            --   i_RFIScale = 16  ==> Amplitude of the filterbank output is unchanged.
            --   i_RFIScale > 16  ==> Amplitude of the filterbank output is reduced.
            i_RFIScale    => RFIScale, -- in std_logic_vector(4 downto 0); 
            -- For monitoring of the output level.
            -- Higher level should keep track of : 
            --   * The total number of frames processed.
            --   * The sum of each of the outputs below. (but note one is superfluous since it can be calculated from the total frames processed and the sum of all the others).
            --      - These sums should be 32 bit values, which ensures wrapping will occur at most once per hour.
            -- For the correlator:
            --   - Each frame corresponds to 3456 fine channels x 2 (H & V polarisations) * 2 (re+im).
            --   - Every fine channel must be one of the categories below, so they will sum to 3456*2*2 = 13824.
            o_overflow    => open, -- hist_overflow(i),     -- out(15:0); -- Number of fine channels which were clipped.
            o_64_127      => open, -- hist_64_127(i),  -- out(15:0); -- Number of fine channels in the range 64 to 128.
            o_32_63       => open, -- hist_32_63(i),   -- out(15:0); -- Number of fine channels in the range 32 to 64.
            o_16_31       => open, -- hist_16_31(i),   -- out(15:0); -- Number of fine channels in the range 16 to 32.
            o_0_15        => open, -- hist_0_15(i),    -- out(15:0); -- Number of fine channels in the range 0 to 15.
            o_virtualChannel => open, -- hist_virtualChannel(i), -- out(8:0);
            o_histogramValid => open  -- hist_valid(i) -- out std_logic -- indicates histogram data is valid.
        );
        
        o_virtualChannel(i) <= FDHeader(i).virtualChannel;
        
    end generate;
    
    o_data <= FDdata;
    o_dataValid <= FDcorDataValid(0);  -- FDPSTDataValid(0) and (1), (2), (3) will be the same.
    
    o_bad_poly(0) <= FDHeader(0).bad_poly or FDHeader(1).bad_poly or FDHeader(2).bad_poly or FDHeader(3).bad_poly;
    o_bad_poly(1) <= FDHeader(4).bad_poly or FDHeader(5).bad_poly or FDHeader(6).bad_poly or FDHeader(7).bad_poly;
    o_bad_poly(2) <= FDHeader(8).bad_poly or FDHeader(9).bad_poly or FDHeader(10).bad_poly or FDHeader(11).bad_poly;
    o_lastChannel <= FDHeader(0).lastChannel;
    o_demap_table_select <= FDHeader(0).demap_table_select;
    
    o_integration <= FDHeader(0).integration;
    o_ctFrame <= FDHeader(0).ctFrame;
    o_headerValid <= headerValid;
    ---------------------------------------------------------------
    -- Registers
    -- 
    
    -- ARGS U55
    gen_u55_args : IF (C_TARGET_DEVICE = "U55") GENERATE 
        filterbank_Reg : entity filterbanks_lib.cor_filterbanks_filterbanks_reg
        port map(
            MM_CLK              => i_axi_clk,   -- in  std_logic;
            MM_RST              => i_axi_rst,   -- in  std_logic;
            SLA_IN              => i_axi_mosi,  -- IN  t_axi4_lite_mosi;
            SLA_OUT             => o_axi_miso,  -- OUT t_axi4_lite_miso;
            CONFIG_FIELDS_RO	=> config_ro,   -- IN  t_config_ro;
            CONFIG_FIELDS_RW    => config_rw,   -- out t_config_rw;
            CONFIG_OUTPUT_DISABLE_IN  => output_disable_i, -- IN  t_config_output_disable_ram_in;
            CONFIG_OUTPUT_DISABLE_OUT => output_disable_o  -- OUT t_config_output_disable_ram_out
        );
    END GENERATE;
    
    -- ARGS Gaskets for V80
    gen_v80_args : IF (C_TARGET_DEVICE = "V80") GENERATE
    
        i_fb_noc : entity noc_lib.args_noc
        generic map (
            G_DEBUG => FALSE
        )
        port map ( 
            i_clk       => i_axi_clk,
            i_rst       => i_axi_rst,
        
            noc_wren    => noc_wren,
            noc_rden    => noc_rden,
            noc_wr_adr  => noc_wr_adr,
            noc_wr_dat  => noc_wr_dat,
            noc_rd_adr  => noc_rd_adr,
            noc_rd_dat  => noc_rd_dat_mux
        );
    
        filterbank_Reg : entity filterbanks_lib.cor_filterbanks_filterbanks_versal
        port map(
            MM_CLK                  => i_axi_clk,   -- in  std_logic;
            MM_RST                  => i_axi_rst,   -- in  std_logic;
    
            noc_wren                => noc_wren,
            noc_rden                => noc_rden,
            noc_wr_adr              => noc_wr_adr,
            noc_wr_dat              => noc_wr_dat,
            noc_rd_adr              => noc_rd_adr,
            noc_rd_dat              => noc_rd_dat_mux,
            
            CONFIG_FIELDS_RO        => config_ro,   -- IN  t_config_ro;
            CONFIG_FIELDS_RW        => config_rw,   -- out t_config_rw;
            CONFIG_OUTPUT_DISABLE_IN    => output_disable_i, -- IN  t_config_output_disable_ram_in;
            CONFIG_OUTPUT_DISABLE_OUT   => output_disable_o  -- OUT t_config_output_disable_ram_out
        );
    
    END GENERATE;


    config_ro.status <= x"00000000";
    config_ro.txCount_eth <= (others => '0');
    config_ro.txcount_corner_turn <= tx_packet_count_ct;
    
    process(i_axi_clk)
    begin
        if rising_edge(i_axi_clk) then
            RFIScale <= config_rw.scaling(4 downto 0);
            reg_reset <= config_rw.config(0);
            reg_reset_del1 <= reg_reset;
            
            -- count of packets going out to the corner turn.
            FDcorDataValidDel <= FDcorDataValid(0);
            if reg_reset = '1' and reg_reset_del1 = '0' then
                tx_packet_count_ct <= (others => '0');
            elsif FDcorDataValid(0) = '1' and FDcorDataValidDel = '0' then
                tx_packet_count_ct <= std_logic_vector(unsigned(tx_packet_count_ct) + 1);
            end if;
            
        end if;
    end process;
    
    output_disable_i.adr <= output_disable_addr;
    output_disable_i.wr_dat <= (others => '0');
    output_disable_i.wr_en <= '0';
    output_disable_i.rd_en <= '1';
    output_disable_i.clk <= i_axi_clk;
    output_disable_i.rst <= '0';
    
end Behavioral;