xbutil reset -d 0
xbutil reset -d 1
xbutil reset -d 2
xbutil reset -d 3
xbutil reset -d 4
xbutil reset -d 5
xbutil reset -d 6
xbutil reset -d 7
xbutil reset -d 8
xbutil reset -d 9
xbutil reset -d 10
xbutil reset -d 11
xbutil reset -d 12
xbutil reset -d 13
xbutil reset -d 14
xbutil reset -d 15
xbutil reset -d 16
xbutil reset -d 17
xbutil reset -d 18
xbutil reset -d 19
