--
-- Package generated by Perentie Matlab packetised model. 
-- Procedures to configure AXI-lite peripherals according to the run1 test case.
-- Creation Date 29-Oct-2020 00:57:40 
library IEEE, axi4_lib, LFAADecode100G_lib, ct_lib;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use axi4_lib.axi4_lite_pkg.all;
use LFAADecode100G_lib.LFAADecode100G_lfaadecode100G_reg_pkg.all;
use ct_lib.ct_atomic_pst_in_reg_pkg.all;

package run1_tb_pkg is 
    procedure setupLFAADecode(signal mm_clk : in std_logic;
                              signal axi_miso : in t_axi4_lite_miso;
                              signal axi_mosi : out t_axi4_lite_mosi);

    procedure setupPST_CT_IN(signal mm_clk : in std_logic;
                             signal axi_miso : in t_axi4_lite_miso;
                             signal axi_mosi : out t_axi4_lite_mosi);

end run1_tb_pkg;

package body run1_tb_pkg is 
    procedure setupLFAADecode(signal mm_clk : in std_logic;
                              signal axi_miso : in t_axi4_lite_miso;
                              signal axi_mosi : out t_axi4_lite_mosi) is
    begin 
        axi_lite_blockwrite(mm_clk, axi_miso, axi_mosi, c_statctrl_vctable_address.base_address + c_statctrl_vctable_address.address, "LFAADecode_VCTable.txt");
        axi_lite_transaction(mm_clk, axi_miso, axi_mosi, c_statctrl_total_stations_address.base_address + c_statctrl_total_stations_address.address, true, x"00000004");
        axi_lite_transaction(mm_clk, axi_miso, axi_mosi, c_statctrl_total_coarse_address.base_address + c_statctrl_total_coarse_address.address, true, x"00000002");
        axi_lite_transaction(mm_clk, axi_miso, axi_mosi, c_statctrl_total_channels_address.base_address + c_statctrl_total_channels_address.address, true, x"00000008");
    end procedure;

    -- added manually; need to fix in the matlab code
    procedure setupPST_CT_IN(signal mm_clk : in std_logic;
                             signal axi_miso : in t_axi4_lite_miso;
                              signal axi_mosi : out t_axi4_lite_mosi) is
    begin 
        -- reset the corner turn to update the parameters.
        --CONSTANT c_config_full_reset_address					: t_register_address := (base_address => 5120, address => 0, offset => 0, width => 1, name => pad("config_full_reset"));
        axi_lite_transaction(mm_clk, axi_miso, axi_mosi, c_config_untimed_framecount_start_address.base_address + c_config_untimed_framecount_start_address.address, true, x"00000000");
        axi_lite_transaction(mm_clk, axi_miso, axi_mosi, c_config_full_reset_address.base_address + c_config_full_reset_address.address, true, x"00000001");
        axi_lite_transaction(mm_clk, axi_miso, axi_mosi, c_config_full_reset_address.base_address + c_config_full_reset_address.address, true, x"00000000");
        
    end procedure;


end run1_tb_pkg;
