----------------------------------------------------------------------------------------------------------
--
--  File Name:              <lib_name>_reg.vhd
--  Type:                   RTL
--  Template Rev:           1.0
--
--  Title:
--  Description:
--
--          Generated by Automatic Register Generation System (ARGS) from <lib>.peripheral.yaml
--
----------------------------------------------------------------------------------------------------------

LIBRARY IEEE, axi4_lib, common_lib, technology_lib;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE axi4_lib.axi4_lite_pkg.ALL;
USE common_lib.common_mem_pkg.ALL;
USE common_lib.common_pkg.ALL;
USE technology_lib.technology_pkg.ALL;
USE technology_lib.technology_select_pkg.ALL;
USE work.<lib_name>_reg_pkg.ALL;

-------------------------------------------------------------------------------
--                              ENTITY STATEMENT                             --
-------------------------------------------------------------------------------

entity <lib_name>_versal_reg is
    GENERIC (g_technology : t_technology := c_tech_select_default);
    PORT (
        MM_CLK              : IN    STD_LOGIC;
        MM_RST              : IN    STD_LOGIC;
        <{user_clocks}>
        noc_wren            : IN STD_LOGIC;
        noc_rden            : IN STD_LOGIC;
        noc_wr_adr          : IN STD_LOGIC_VECTOR(17 DOWNTO 0);
        noc_wr_dat          : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
        noc_rd_adr          : IN STD_LOGIC_VECTOR(17 DOWNTO 0);
        noc_rd_dat          : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
        <{slave_ports}>
        );
end <lib_name>_versal_reg;

-------------------------------------------------------------------------------
--                           ARCHITECTURE STATEMENT                          --
-------------------------------------------------------------------------------

architecture rtl of <lib_name>_versal_reg is

    ---------------------------------------------------------------------------
    --                CONSTANT, TYPE AND GENERIC DEFINITIONS                 --
    ---------------------------------------------------------------------------
    CONSTANT c_byte_w       : NATURAL := 8;
    CONSTANT c_addr_w       : NATURAL := <adr_w>;
    CONSTANT c_dat_w        : NATURAL := <dat_w>;

    <{c_mm_reg}>


    ---------------------------------------------------------------------------
    --                          SIGNAL DECLARATIONS                          --
    ---------------------------------------------------------------------------

    <{signal_declarations}>

    SIGNAL rd_dat               : STD_LOGIC_VECTOR(c_dat_w-1 DOWNTO 0);
    SIGNAL wr_dat               : STD_LOGIC_VECTOR(c_dat_w-1 DOWNTO 0);
    SIGNAL wr_val_sum           : STD_LOGIC;
    SIGNAL rd_val_sum           : STD_LOGIC;
    SIGNAL reg_wren             : STD_LOGIC;
    SIGNAL reg_rden             : STD_LOGIC;
    SIGNAL wr_adr               : STD_LOGIC_VECTOR(c_addr_w-1 DOWNTO 0);
    SIGNAL rd_adr               : STD_LOGIC_VECTOR(c_addr_w-1 DOWNTO 0);
    SIGNAL rd_busy_sum          : STD_LOGIC;
    SIGNAL wr_busy_sum          : STD_LOGIC;


    ---------------------------------------------------------------------------
    --                        COMPONENT DECLARATIONS                         --
    ---------------------------------------------------------------------------


begin

    ---------------------------------------------------------------------------
    --                        INSTANTIATE COMPONENTS                         --
    ---------------------------------------------------------------------------

    rd_dat <=
    <{rd_dat}>

    reg_wren        <= noc_wren;
    reg_rden        <= noc_rden;
    wr_adr          <= noc_wr_adr(c_addr_w-1 DOWNTO 0);
    wr_dat          <= noc_wr_dat;
    rd_adr          <= noc_rd_adr(c_addr_w-1 DOWNTO 0);
    noc_rd_dat      <= rd_dat;


    <{common_reg_inst}>

    ---------------------------------------------------------------------------
    --                  INPUT CONCURRENT SIGNAL ASSIGNMENTS                  --
    ---------------------------------------------------------------------------

    <{input_statements}>

    ---------------------------------------------------------------------------
    --                         CONCURRENT PROCESSES                          --
    ---------------------------------------------------------------------------

    ---------------------------------------------------------------------------
    --  Process:  <entity>_PROCESS
    --  Purpose:
    --  Inputs:
    --  Outputs:
    ---------------------------------------------------------------------------


    ---------------------------------------------------------------------------
    --                 OUTPUT CONCURRENT SIGNAL ASSIGNMENTS                  --
    ---------------------------------------------------------------------------

    <{output_statements}>

end rtl;

-------------------------------------------------------------------------------
--                          CONFIGURATION STATEMENT                          --
-------------------------------------------------------------------------------

--configuration <configuration> of <entity> is
--<{configuration_statements}>
--end <configuration>;

-------------------------------------------------------------------------------


